name: my_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - scikit-learn
  - scipy
  - pytorch
  - pandas
  - pip:
    - torch
    - scikit-learn
    - pandas
